#!/bin/bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${POSTGRES_SCRAPER_USER}') THEN
    CREATE ROLE ${POSTGRES_SCRAPER_USER} LOGIN PASSWORD '${POSTGRES_SCRAPER_PASSWORD}';
  ELSE
    ALTER ROLE ${POSTGRES_SCRAPER_USER} WITH PASSWORD '${POSTGRES_SCRAPER_PASSWORD}';
  END IF;

  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${POSTGRES_GRAFANA_USER}') THEN
    CREATE ROLE ${POSTGRES_GRAFANA_USER} LOGIN PASSWORD '${POSTGRES_GRAFANA_PASSWORD}';
  ELSE
    ALTER ROLE ${POSTGRES_GRAFANA_USER} WITH PASSWORD '${POSTGRES_GRAFANA_PASSWORD}';
  END IF;
END
\$\$;
SQL
