#!/bin/bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_SCRAPER_USER};
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_GRAFANA_USER};
GRANT USAGE ON SCHEMA public TO ${POSTGRES_SCRAPER_USER};
GRANT USAGE ON SCHEMA public TO ${POSTGRES_GRAFANA_USER};
GRANT INSERT ON sen_readings TO ${POSTGRES_SCRAPER_USER};
GRANT SELECT (collected_at) ON sen_readings TO ${POSTGRES_SCRAPER_USER};
GRANT SELECT ON sen_readings, sen_5min TO ${POSTGRES_GRAFANA_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${POSTGRES_GRAFANA_USER};
SQL
